//Bismillah

export const cardsData = [
    { definition: "The Majestic. The Supreme. Al-Mutakabbir", word: "ُالْمُتَكَبِّر" },
    { definition: "The Compellor. The Restorer. Al-Jabbar", word: "الْجَبَّارُ" },
    { definition: "The Mighty One. The All Mighty. Al-Aziz", word: "الْعَزِيزُ" },
    { definition: "The Protector. The Preserver of Safety. Al-Muhaymin", word: "الْمُهَيْمِنُ" },
    { definition: "The Giver of Peace. The Infuser of Faith. Al-Mu'min", word: "الْمُؤْمِنُ" },
    { definition: "The Giver of Peace. The Source of Peace. The Flawless. As-Salam", word: "السَّلاَمُ" },
    { definition: "Free From All Blemishes. The Most Sacred. Al-Quddus", word: "ُالْقُدُّوسُ" },
    { definition: "The Sovereign. The King. Al-Malik", word: "الْمَلِكُ" },
    { definition: "The Most Merciful. Ar-Rahim", word: "الرَّحِيمُ" },
    { definition: "The Compassionate. The Beneficent. Ar-Rahman", word: "الرَّحْمَنُ" },
    { definition: "The Constrictor. The Withholder. Al-Qaabid", word: "الْقَابِضُ" },
    { definition: "The All Knowing. Al-Aleem", word: "اَلْعَلِيْمُ" },
    { definition: "The Remover of Difficulties. the Supreme Solver. Al-Fattaah", word: "الْفَتَّاحُ" },
    { definition: "The Provider. Ar-Razzaq", word: "ُالرَّزَّاقُ"},
    { definition: "The Supreme Bestower. Al-Wahhab", word: "الْوَهَّابُ"},
    { definition: "The Dominant. The All-Prevailing One. Al-Qahhar", word: "الْقَهَّارُ" },
    { definition: "The Great Forgiver. The Constant Forgiver. Al-Ghaffar", word: "الْغَفَّارُ" },
    { definition: "The Fashioner. Al-Musawwir", word: "الْمُصَوِّرُ" },
    { definition: "The Inventor. Al-Baari", word: "الْبَارِئُ" },
    { definition: "The Creator. The Maker. Al-Khaaliq", word: "الْخَالِقُ" },
    { definition: "The Subtle One. The Most Gentle. Al-Latif", word: "ُاللَّطِيفُ" },
    { definition: "The Just. Al-Adl", word: "الْعَدْلُ" },
    { definition: "The Impartial Judge. Al-Hakam", word: "الْحَكَمُ" },
    { definition: "The All-Seeing. Al-Baseer", word: "الْبَصِيرُ"},
    { definition: "The All-Hearing. As-Sami", word: "السَّمِيعُ" },
    { definition: "The Dishonorer. Al-Mudheell, Al-Muzil", word: "ٱلْمُذِلُّ" },
    { definition: "The Honorer. The Bestower. Al-Mu'izz", word: "الْمُعِزُّ" },
    { definition: "The Exalter. The Elevator. Ar-Raafi'", word: "الرَّافِعُ" },
    { definition: "The Reducer. The Abaissier (Humbler). Al-Khaafidh", word: "الْخَافِضُ" },
    { definition: "The Expander. The Extender. Al-Baasit", word: "الْبَاسِطُ" },
    { definition: "The Reckoner. al-Haseeb", word: "اﻟْﺣَسِيبُ" },
    { definition: "The Controller of Things. The Sustainer. Al-Muqeet", word: "المُقيِت" },
    { definition: "The Preserver. Al-Hafeez", word: "الْحَفِيظُ" },
    { definition: "The Most Great. Al-Kabeer", word: "الْكَبِيرُ" },
    { definition: "The Most High. The Exalted. Al-'Alee", word: "ُالْعَلِيُّ" },
    { definition: "The Most Appreciative. Ash-Shakoor", word: "الشَّكُورُ" },
    { definition: "The All-Forgiving. The Great Forgiver. Al-Ghafoor", word: "الْغَفُور" },
    { definition: "The Great One. The Magnificent. The Supreme. Al-'Adheem", word: "الْعَظِيمُ" },
    { definition: "The Most Forbearing. Al-Haleem", word: "الْحَلِيمُ" },
    { definition: "The All-Aware. Al-Khabeer", word: "الْخَبِيرُ" },
    { definition: "The Witness. The All Observing Witnessing. Ash-Shaheed", word: "الشَّهِيدُ" },
    { definition: "The Resurrector. The Infuser of New Life. Al-Ba'ith", word: "ُالْبَاعِثُ" },
    { definition: "The Most Honorable. The Glorious. Al-Majeed", word: "الْمَجِيدُ" },
    { definition: "The Loving. Al-Wadood", word: "الْوَدُودُ" },
    { definition: "The All-Wise. Al-Hakeem", word: "الْحَكِيمُ" },
    { definition: "The All-Embracing. The All-Encompassing. The Boundless. Al-Waasi'", word: "الْوَاسِعُ" },
    { definition: "The Responsive. Al-Mujeeb", word: "ٱلْمُجِيبُ" },
    { definition: "The Watchful. Ar-Raqeeb", word: "الرَّقِيبُ" },
    { definition: "The Benevolent. The Most Generous. The Most Esteemed. Al-Kareem", word: "الْكَرِيمُ" },
    { definition: "The Majestic. Al-Jaleel", word: "الْجَلِيلُ" },
    { definition: "The Giver of Live. Al-Muhyi", word: "الْمُحْيِي" },
    { definition: "The Restorer. The Reinstater. Al-Mu'eed", word: "ٱلْمُعِيدُ" },
    { definition: "The Originator. The Initiator. Al-Mubdi", word: "الْمُبْدِئُ" },
    { definition: "The One Who Records. The All-Enumerating. The Counter. Al-Muhsee", word: "الْمُحْصِي" },
    { definition: "The Praiseworthy. Al-Hameed", word: "الْحَمِيدُ" },
    { definition: "The Protecting Friend. Al-Wali", word: "	الْوَلِيُّ" },
    { definition: "The Firm. The Steadfast. Al-Mateen", word: "الْمَتِينُ" },
    { definition: "The All-Strong. Al-Qawiyy", word: "الْقَوِيُ" },
    { definition: "The Trustee. The Disposer of Affairs. Al-Wakeel", word: "الْوَكِيلُ" },
    { definition: "The Absolute Truth. Al-Haqq", word: "الْحَقُ" },
    { definition: "The Powerful. Al-Muqtadir", word: "الْمُقْتَدِرُ" },
    { definition: "The Able. The Omnipotent. Al-Qadir", word: "الْقَادِرُ" },
    { definition: "The Eternal Refuge. The Satisfier of Needs. As-Samad", word: "الصَّمَدُ" },
    { definition: "The Only One. The Unique. Al-Ahad", word: "اَلاَحَدُ" },
    { definition: "The Alone. The One. Al-Waahid", word: "الْواحِدُ" },
    { definition: "The Noble. The Magnificent. The Illustrious. Al-Maajid", word: "الْمَاجِدُ" },
    { definition: "The Finder. The Perceiver. Al-Waajid", word: "الْوَاجِدُ" },
    { definition: "The Sustainer. The Self-Subsisting. Al-Qayyoom", word: "الْقَيُّومُ" },
    { definition: "The Ever-Living. Al-Hayu", word: "الْحَيُّ" },
    { definition: "The Giver of Death. The Creator of Death. Al-Mumeet", word: "ُاَلْمُمِيتُ" },
    { definition: "The Acceptor of Repentance. The Ever-Pardoning. At-Tawwab", word: "التَّوَابُ" },
    { definition: "The Source of All Goodness. Al-Barr", word: "الْبَرُّ" },
    { definition: "The Most Exalted. The Self Exalted. Al-Muta'ali", word: "الْمُتَعَالِي" },
    { definition: "The Sole Governor. Al-Waali", word: "الْوَالِي" },
    { definition: "The Hidden. The Knower of the Hidden. Al-Baatin", word: "الْبَاطِنُ" },
    { definition: "The Manifest. Az-Zahir", word: "الظَّاهِرُ" },
    { definition: "The Last. Al-AAkhir", word: "ُالآخِرُ" },
    { definition: "The First. Al-Awwal", word: "الأوَّلُ" },
    { definition: "The Delayer. Al-Mu'akhkhir", word: "الْمُؤَخِّرُ" },
    { definition: "The Expediter. The Promoter. Al-Muqaddim", word: "الْمُقَدِّمُ" },
    { definition: "The Enricher. Al-Mughni", word: "ٱلْمُغْنِيُّ" },
    { definition: "The Free of Need. The Self-Sufficient. The Wealthy. Al-Ghaniyy", word: "ٱلْغَنيُّ" },
    { definition: "The Gatherer. The Uniter. Al-Jaami'", word: "الْجَامِعُ" },
    { definition: "The Equitable. The Just One. Al-Muqsit", word: "ُالْمُقْسِطُ" },
    { definition: "The Lord of Majesty and Bounty. The Lord of Glory and Honor. Dhul-jalaali Wal-Ikraam", word: "ذُوالْجَلاَلِ وَالإكْرَامِ" },
    { definition: "The Eternal Owner of Sovereighty. The Master of the Kingdom. The Owner of the Dominion. Maalik-ul-Mulk", word: "مَالِكُ ٱلْمُلْكُ" },
    { definition: "The Compassionate. The Most Kind. Ar-Ra'oof", word: "الرَّؤُوفُ" },
    { definition: "The Pardoner. Al-'Afuww", word: "العَفُوُ" },
    { definition: "The Avenger. Al-Muntaqim", word: "الْمُنْتَقِمُ" },
    { definition: "The Patient. The Forbearing. As-Saboor", word: "الصَّبُورُ" },
    { definition: "The Guide of The Right Path. The Infallible Teacher. Ar-Rasheed", word: "ُالرَّشِيدُ" },
    { definition: "The Supreme Inheritor. The One Who Remain After All Has Past. Al-Waarith", word: "الْوَارِثُ" },
    { definition: "The Everlasting. Al-Baaqi", word: "اَلْبَاقِي" },
    { definition: "The Inventor of Unmatchables. The Incomparable Originator. Al-Badee'", word: "الْبَدِيعُ" },
    { definition: "The Guide. Al-Haadi", word: "الْهَادِي" },
    { definition: "The Lightener. The Illuminator. An-Nur", word: "النُّورُ" },
    { definition: "The Propitious. The Benefactor. An-Nafi'", word: "النَّافِعُ" },
    { definition: "The Distressor. Ad-Darr", word: "ٱلضَّارُّ" },
    { definition: "The Preventor. The Withholder. Al-Mani'", word: "اَلْمَانِعُ" },
];



